import time
Nomen11 = input("Nomen mehrzahl:")
time.sleep(0.5)
Adjek = input("Adjektiv:")
time.sleep(0.5)
Nomen = input("Nomen mehrzahl:")
time.sleep(0.5)
time.sleep(0.5)
Nomen1 = input("Nomen mehrzahl:")
verb = input("Adjektiv:")
time.sleep(0.5)
nom0 = input("Nomen mehrzahl:")
Nomen = input("Nomen:")
time.sleep(0.5)
nom = input("Nomen mehrzahl:")
time.sleep(0.5)
print("")
time.sleep(0.5)
print(Nomen + " sind " +verb )
time.sleep(2)
print(nom0 +  " sind " + Adjek )
time.sleep(2)
print(Nomen1 + " lieben " + nom)
time.sleep(0.5)
print("Den sie sind " + Nomen11)
